<?php
// Variables
return [
  "creatorName" => "Ghotme",
  "creatorUrl" => "https://ghotme.com.br",
  "templateName" => "Ghotme ERP",
  "templateSuffix" => "Sistema de Gestão Inteligente",
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => "Ghotme ERP - O sistema de gestão que se molda ao seu negócio.",
  "templateKeyword" => "erp, gestão, oficina, pet shop, assistência técnica, finanças, estoque",
  "licenseUrl" => "https://ghotme.com.br/termos",
  "livePreview" => "https://ghotme.com.br",
  "productPage" => "https://ghotme.com.br",
  "support" => "https://ghotme.com.br/suporte",
  "moreThemes" => "",
  "ogTitle" => "Ghotme ERP - Gestão Inteligente e Flexível",
  "ogImage" => "https://ghotme.com.br/assets/img/og-image.png",
  "ogType" => "website",
  "documentation" => "https://ghotme.com.br/docs",
  "generator" => "Ghotme",
  "changelog" => "https://ghotme.com.br/changelog",
  "repository" => "",
  "gitRepo" => "ghotme-erp",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "https://www.facebook.com/ghotme",
  "twitterUrl" => "https://x.com/ghotme",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => "https://www.instagram.com/ghotme/"
];
